---
editor_options: 
  chunk_output_type: console
---

# Scenario 1: Random walks

```{r}
# load packages
library(data.table)
library(ggplot2)
```

## Demonstrate landscape

```{r}
# patchy landscape
l = ecoevomove2::get_test_landscape(
    nItems = 450,
    landsize = 30,
    nClusters = 30,
    clusterSpread = 0.5,
    regen_time = 100
)

ggplot(l)+
    geom_point(
        aes(
            x, y
        )
    )
```

## Random walk on patchy landscapes

```{r}
# run scenarios
data_random <- lapply(seq(20), function(x) {
  ecoevomove2::model_case_2(
    scenario = 0,
    landsize = 30,
    nItems = 450,
    clusterSpread = 0.5,
    nClusters = 30,
    regen_time = 100,
    tmax = 400,
    handling_time = 5,
    popsize = 200,
    genmax = 1,
    dispersal = 10,
    range_perception = 1.0,
    mProb = 0.01,
    mSize = 0.01,
    nThreads = 1
  )
})
```

```{r}
# examine intake in random movement
data_random_intake = lapply(data_random, slot, "trait_data")

# assign replicate
data_random_intake = Map(
    data_random_intake, seq(length(data_random_intake)),
    f = function(df, n) {
        setDT(df)
        df[, replicate := as.factor(n)][]
    }
)

data_random_intake = rbindlist(data_random_intake)

# add details
data_random_intake[, landscape := "patchy"]
data_random_intake[, type := "random"]

# save trait data
fwrite(
    data_random_intake,
    file = "inst/data/data_traits_random_patchy.csv"
)
```

Networks from random walk on patchy landscape.

```{r}
networks_random = lapply(data_random, ecoevomove2::make_network, weight_threshold = 3)

# save networks
saveRDS(networks_random, file = "inst/data/networks_random_patchy.Rds")
```

## Random walks, homogeneous resource landscapes

```{r}
# run scenarios
data_random <- lapply(seq(20), function(x) {
  ecoevomove2::model_case_2(
    scenario = 0,
    landsize = 30,
    nItems = 450,
    clusterSpread = 0.5,
    nClusters = 90,
    regen_time = 100,
    tmax = 400,
    handling_time = 5,
    popsize = 200,
    genmax = 1,
    dispersal = 10,
    range_perception = 1.0,
    mProb = 0.01,
    mSize = 0.01,
    nThreads = 1
  )
})
```

```{r}
# examine intake in random movement
data_random_intake = lapply(data_random, slot, "trait_data")

# assign replicate
data_random_intake = Map(
    data_random_intake, seq(length(data_random_intake)),
    f = function(df, n) {
        setDT(df)
        df[, replicate := as.factor(n)][]
    }
)

data_random_intake = rbindlist(data_random_intake)

# add details
data_random_intake[, landscape := "homog"]
data_random_intake[, type := "random"]

# save trait data
fwrite(
    data_random_intake,
    file = "inst/data/data_traits_random_homog.csv"
)
```

Networks from random walk on homogeneous landscape.

```{r}
networks_random = lapply(data_random, ecoevomove2::make_network, weight_threshold = 3)

# save networks
saveRDS(networks_random, file = "inst/data/networks_random_homog.Rds")
```
