---
editor_options: 
  chunk_output_type: console
---

# Run network SIR models

Load libraries.

```{r}
library(data.table)
library(igraph)
library(tidygraph)

# for plotting
library(ggplot2)
```

## Prepare parameters

```{r}
# disease parameters
beta = c(2)
gamma = c(1)
threshold = c(12)
```

## Load saved networks

```{r}
network_files = list.files(
  path = "inst/data/",
  pattern = "networks",
  full.names = TRUE
)
```

## Run SIR models

```{r}
sc_repl = seq(20) # the number of replicates

data_sir_models = Map(
  network_files,
  f = function(file) {
    
    # detect sim type and landscape type
    type = stringr::str_extract(file, "(unevolved)|(evolved)|(optimal)|(random)|(2pref)|(pref2_unevolved)")
    landscape = stringr::str_extract(file, "(patchy)|(homog)")
    dispersal = fifelse(stringr::str_detect(file, "global"), "global", "local")
    dispersal = fifelse(type %in% c("evolved", "unevolved", "2pref", "pref2_unevolved"), dispersal, "global")
    
    # load networks
    data_nt = readRDS(file)
    
    # run sir models
    sir_data = lapply(data_nt, function(g) {
      
      # filter for edge weight
      g = g %>% 
        activate(edges) %>% 
        filter(weight > threshold)
      
      sir_model_runs = igraph::sir(
        graph = g,
        beta = beta, gamma = gamma, no.sim = 25
      ) |>
        ecoevomove2::handle_sir_data(digits = 1)
      
      sir_model_runs
    }
    )
    
    # add replicate
    sir_data = Map(
      sir_data, sc_repl,
      f = function(df, rpl) {
        df[, sc_repl := rpl][]
      }
    )
    
    # bind all rows
    sir_data = rbindlist(sir_data)
    sir_data[, c("type", "landscape", "dispersal") := list(
      type, landscape, dispersal
    )][]
    
  }
)

# bind all data together and save
data_sir_models = rbindlist(data_sir_models)
fwrite(
  data_sir_models,
  file = "inst/data/data_sir_thr_12.csv"
)
```

Sanity check.

```{r}
ggplot(data_sir_models[time < 9 & landscape == "patchy"])+
  stat_summary(
    aes(
      time, mean,
      col = class
    ),
    # geom = "line",
    # size = 1
  )+
  # scale_x_sqrt(
  #   breaks = c(
  #     0.1, 0.5,
  #     seq(1, 12, 1)
  #   )
  # )+
  facet_grid(
    rows = vars(type),
    cols = vars(dispersal)
  )
```
